---
- hosts: all # run on the "all" hosts category from ansible-hosts.txt
  # become means be superuser
  become: true
  remote_user: centos
  tasks:
  - name: Install required dependiences
    yum: name={{ item }} state=present
    with_items:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

  - name: Add docker repo /etc/yum.repos.d
    shell: yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
      #register: result # 把这个任务的执行结果存到变量result

  - name: Install docker and its dependecies
    yum: name=docker-ce state=present
      #when: result|success # 如果上面的result为success则执行这个安装任务

  - name: Start docker service
    systemd: name=docker state=started enabled=true

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none
  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb >= 0

  - name: ADD k8s repo
    copy: 
      src: /opt/k8s/kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo

  - name: Install kubelet, kubeadm and kubectl
    yum:
      name: "{{ packages }}"
      state: present
    vars:
      packages: 
        - kubelet-1.23.6-0
        - kubeadm-1.23.6-0
        - kubectl-1.23.6-0
  
  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  # 添加centos用户
  - name: add centos user to docker
    user:
      name: centos
      group: docker

  # 重启
  - name: reboot to apply swap disable
    reboot:
      reboot_timeout: 180 #allow 3 minutes for reboot to happen
  - name: stop and disable firewalld 
    service: name=firewalld state=stopped enabled=False
